
import os

configfile: "config/config.yaml"

ids = os.listdir(config["input_folder"])
ids = [i for i in ids if i != "misc"]

include: "rules/assembly.smk"
include: "rules/quality_control.smk"


rule all:
	input:
		expand(rules.assembly_stats.output, id = ids)